GoaGaraget/Models/ParkedVehicle.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Data.Entity;
using GoaGaraget.DataAccessLayer;
using System.Web.Mvc;

namespace GoaGaraget.Models
{
    public class ValidateUniqueRegistrationNumber : ValidationAttribute
    {
        private GarageDbContext _Db = new GarageDbContext();
        public bool IsParked(string regNr)
        {
            return _Db.ParkedVehicles.Any<ParkedVehicle>(v => (v.RegNumber == regNr));
        }
        protected override ValidationResult IsValid(object value, ValidationContext validationContext)
        {
            if (IsParked((string)value))
                return new ValidationResult("Car is already in Garage");
            else
                return ValidationResult.Success;
        }

    }


    //public enum VehicleType { Car, Truck, Lorry, Motorcycle, Boat, Airplane }
    [OutputCacheAttribute(VaryByParam ="*",Duration =0,NoStore =true)]
    public class ParkedVehicle
    {
        [Required(ErrorMessage = "Id is required")]
        public int Id { get; set; }

        [DisplayName("Plate number")]
        [RegularExpression(@"[a-zA-ZÅÄÖ]{1,3}[0-9]{1,3}", ErrorMessage = "Please use correct format ABC123")]
        [Required(ErrorMessage = "Plate number is required")]
        [ValidateUniqueRegistrationNumber]
        public string RegNumber { get; set; }

        [DisplayName("Vehicle size")]
        [RegularExpression(@"[1-5]{1}", ErrorMessage = "Limited to 1-5 spaces")]
        [Required(ErrorMessage = "Plate number is required")]
        public int Size { get; set; } = 1;

        [DisplayName("Vehicle color")]
        [Required(ErrorMessage = "Please select a color")]
        public string Color { get; set; }

        [DisplayName("Vehicle type")]
        [Required(ErrorMessage = "Please select a type")]
        public int VehicleTypeId { get; set; }
        public virtual VehicleType VehicleType { get; set; }

        [DisplayName("Vehicle brand")]
        [Required(ErrorMessage = "Please specify brand")]
        [StringLength(30, ErrorMessage = "Please limit to 30 characters")]
        public string Brand { get; set; }

        [DisplayName("How many wheels")]
        [Required(ErrorMessage = "Please specify number of wheels")]
        public int NumberOfWheels { get; set; }

        [Required(ErrorMessage = "Date is required")]
        public DateTime CheckinDate { get; set; }

        public int MemberId { get; set; }
        public virtual Member Member { get; set; }

        public virtual ICollection<ParkingSpace> ParkingSpaces { get; set; }
        

        public ParkedVehicle()
        {
            this.ParkingSpaces = new List<ParkingSpace>();
        }
        public ParkedVehicle(Member member, string regNr, string color, VehicleType vehicleType, string brand, int numberOfWheels, DateTime checkinDate)
        {
            this.Member = member;
            this.RegNumber = regNr;
            this.Size = vehicleType.Size;
            this.Color = color;
            this.VehicleType = vehicleType;
            this.Brand = brand;
            this.NumberOfWheels = numberOfWheels;
            this.CheckinDate = checkinDate;
            this.ParkingSpaces = new List<ParkingSpace>();
        }
    }
}

GoaGaraget/Controllers/ParkedVehiclesController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GoaGaraget.DataAccessLayer;
using GoaGaraget.Models;

namespace GoaGaraget.Controllers
{
    public class ParkedVehiclesController : Controller
    {
        private GarageDbContext db = new GarageDbContext();

        // GET: ParkedVehicles
        public ActionResult Index()
        {
            return View(db.ParkedVehicles.ToList());
        }
        public ActionResult SimpleIndex()
        {
            List<ParkedVehicleListModel> pvlm = new ParkedVehiclesListModel().Simplify(db.ParkedVehicles.ToList());
            return View(pvlm);
        }

        // GET: ParkedVehicles/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ParkedVehicle parkedVehicle = db.ParkedVehicles.Find(id);
            if (parkedVehicle == null)
            {
                return HttpNotFound();
            }
            return View(parkedVehicle);
        }

        // GET: ParkedVehicles/Statistics/5?
        public ActionResult Statistics(int? id)
        {
            if (id == null)
            {
                StatisticModel sm = new StatisticModel(db.ParkedVehicles.ToList());
                return PartialView("_Statistics", sm);
            }
            else
            {
                ParkedVehicle parkedVehicle = db.ParkedVehicles.Find(id);
                if (parkedVehicle != null)
                {
                    StatisticModel sm = new StatisticModel(parkedVehicle);
                    return View("Statistics", sm);
                }
            }
            return View("Index");
        }

        // GET: ParkedVehicles/Park/5
        public ActionResult Park(int? id)
        {

            if (id == null)
            {
                return View();
            }
            else
            {
                ParkedVehicle parkedVehicle = db.ParkedVehicles.Find(id);
                ParkingSpace[] parkingSpaces = db.ParkingSpaces.ToArray();
                ParkingModel pm = new ParkingModel();
                pm.ParkedVehicle = parkedVehicle;
                if (parkedVehicle.VehicleType.Id == 2)
                {
                    pm.AvailableParkingSpaces = new Functionalities.DoIt().GetAvailableMCParkingSpaces(parkingSpaces);

                }
                else
                {
                    pm.AvailableParkingSpaces = new Functionalities.DoIt().GetAvailableParkingSpaces(parkedVehicle.Size, parkingSpaces);
                }
                pm.ParkedVehicleId = (int)id;
                ViewBag.ParkingSpaceId = new SelectList(pm.AvailableParkingSpaces, "Id", "Id");
                //ViewBag.ParkedVehicleId = new SelectList(, "Id", "RegNumber", id);

                if (parkingSpaces[0] != null) pm.ParkingSpaceId = parkingSpaces[0].Id;

                if (parkedVehicle != null)
                {
                    if (pm.AvailableParkingSpaces.Count > 0)
                        return View(pm);
                    else
                        return View(pm); //RedirectToActionPermanent("ParkingFull", "Home");
                }


            }
            return View("Index");
        }

        // POST : ParkedVehicles/Park/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Park([Bind(Include = "ParkedVehicleId, ParkingSpaceId")] ParkingModel parkingModel)
        {
            if (ModelState.IsValid)
            {
                ParkedVehicle parkedVehicle = db.ParkedVehicles.Find(parkingModel.ParkedVehicleId);
                ParkingSpace parkingSpace;
                parkingModel.CreatedAt = DateTime.Now;
                int i = 0;
                if (parkedVehicle.VehicleType.Id == 2)
                {
                    parkingSpace = db.ParkingSpaces.Find(parkingModel.ParkingSpaceId);
                    parkingSpace.IsEmpty = false;
                    parkingSpace.IsMcParkingSpace = true;
                    parkedVehicle.ParkingSpaces.Add(parkingSpace);
                    db.Entry(parkingSpace).State = EntityState.Modified;
                    //parkingSpace.ParkedVehicles.Add(parkedVehicle);
                    parkedVehicle.CheckinDate = DateTime.Now;
                }
                else
                {
                    do
                    {
                        parkingSpace = db.ParkingSpaces.Find(parkingModel.ParkingSpaceId + i);
                        parkingSpace.IsEmpty = false;
                        parkedVehicle.ParkingSpaces.Add(parkingSpace);
                        db.Entry(parkingSpace).State = EntityState.Modified;
                        parkingSpace.ParkedVehicles.Add(parkedVehicle);
                        i++;
                    } while (i < parkedVehicle.Size);
                    parkedVehicle.CheckinDate = DateTime.Now;
                }
                db.Entry(parkedVehicle).State = EntityState.Modified;
                db.Configuration.ValidateOnSaveEnabled = false;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(parkingModel);
        }

        // GET: ParkedVehicles/Create
        public ActionResult Create()
        {
            Functionalities.DoIt doIt = new Functionalities.DoIt();
            //ViewBag.MemberId = new SelectList(db.Members, "Id", "PersonNumber");
            //ViewBag.VehicleTypeId = new SelectList(db.VehicleTypes, "Id", "Name");

            ParkedVehicleViewModel pvvm = new ParkedVehicleViewModel();
            pvvm.Members = new SelectList(db.Members.ToList(), "Id", "Firstname");
            pvvm.VehicleTypes = new SelectList(db.VehicleTypes.ToList(), "Id", "Name");

            return View(pvvm);
        }

        // POST: ParkedVehicles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MemberId,RegNumber,Color,VehicleTypeId,Brand,NumberOfWheels")] ParkedVehicleViewModel pvvm)
        {
            VehicleType vt = db.VehicleTypes.Single(v => v.Id == pvvm.VehicleTypeId);
            ParkedVehicle parkedVehicle = new ParkedVehicle(pvvm.Member, pvvm.RegNumber, pvvm.Color, vt, pvvm.Brand, pvvm.NumberOfWheels, DateTime.Now);
            parkedVehicle.Member = db.Members.Single(m => m.Id == pvvm.MemberId);
            parkedVehicle.VehicleType = vt;

            if (ModelState.IsValid)
            {
                parkedVehicle.Size = parkedVehicle.VehicleType.Size;
                db.ParkedVehicles.Add(parkedVehicle);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            pvvm.Members = new SelectList(db.Members.ToList(), "Id", "PersonNumber");
            pvvm.VehicleTypes = new SelectList(db.VehicleTypes.ToList(), "Id", "Name");
            return View(pvvm);
        }



        // GET: ParkedVehicles/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ParkedVehicle parkedVehicle = db.ParkedVehicles.Find(id);
            if (parkedVehicle == null)
            {
                return HttpNotFound();
            }
            ParkedVehicleInputModel parkedVehicleInput = new ParkedVehicleInputModel
            {
                Id = parkedVehicle.Id,
                RegNumber = parkedVehicle.RegNumber,
                Color = parkedVehicle.Color,
                Brand = parkedVehicle.Brand,
                NumberOfWheels = parkedVehicle.NumberOfWheels
            };
            return View(parkedVehicleInput);
        }

        // POST: ParkedVehicles/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,RegNumber,Color,Type,Brand,NumberOfWheels,CheckinDate")] ParkedVehicleInputModel parkedVehicleInput)
        {
            if (ModelState.IsValid)
            {
                ParkedVehicle parkedVehicle = db.ParkedVehicles.Find(parkedVehicleInput.Id);
                parkedVehicle.Id = parkedVehicleInput.Id;
                parkedVehicle.Color = parkedVehicleInput.Color;
                parkedVehicle.Brand = parkedVehicleInput.Brand;
                parkedVehicle.NumberOfWheels = parkedVehicleInput.NumberOfWheels;
                db.Entry(parkedVehicle).State = EntityState.Modified;
                db.Configuration.ValidateOnSaveEnabled = false;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(parkedVehicleInput);
        }

        // GET: ParkedVehicles/Checkout/5
        public ActionResult Checkout(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ParkedVehicle parkedVehicle = db.ParkedVehicles.Find(id);
            if (parkedVehicle == null)
            {
                return HttpNotFound();
            }
            Receipt receipt = new Receipt();
            receipt.ParkedVehicle = parkedVehicle;
            new Functionalities.Calculate().UpdateReceipt(receipt);
            ViewBag.visitHours = (receipt.CheckoutAt - receipt.CheckinAt).Hours;
            ViewBag.visitMinutes = (receipt.CheckoutAt - receipt.CheckinAt).Minutes;
            return View(receipt);
        }

GoaGaraget/Controllers/ParkingSpacesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GoaGaraget.DataAccessLayer;
using GoaGaraget.Models;

namespace GoaGaraget.Controllers
{
    public class ParkingSpacesController : Controller
    {
        private GarageDbContext db = new GarageDbContext();

        // GET: ParkingSpaces
        public ActionResult Index()
        {
            var parkingSpaces = db.ParkingSpaces.Include(p => p.Garage);
            return View(parkingSpaces.ToList());
        }

        // GET: ParkingSpaces/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ParkingSpace parkingSpace = db.ParkingSpaces.Find(id);
            if (parkingSpace == null)
            {
                return HttpNotFound();
            }
            return View(parkingSpace);
        }

        // GET: ParkingSpaces/Create
        public ActionResult Create()
        {
            ViewBag.GarageId = new SelectList(db.Garages, "Id", "Name");
            return View();
        }

        // POST: ParkingSpaces/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Price,IsEmpty,IsMcParkingSpace,TotalIncome,VisitorCount,AverageTime,McCountMax,GarageId")] ParkingSpace parkingSpace)
        {
            if (ModelState.IsValid)
            {
                db.ParkingSpaces.Add(parkingSpace);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.GarageId = new SelectList(db.Garages, "Id", "Name", parkingSpace.GarageId);
            return View(parkingSpace);
        }

        // GET: ParkingSpaces/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ParkingSpace parkingSpace = db.ParkingSpaces.Find(id);
            if (parkingSpace == null)
            {
                return HttpNotFound();
            }
            ViewBag.GarageId = new SelectList(db.Garages, "Id", "Name", parkingSpace.GarageId);
            return View(parkingSpace);
        }

        // POST: ParkingSpaces/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Price,IsEmpty,IsMcParkingSpace,TotalIncome,VisitorCount,AverageTime,McCountMax,GarageId")] ParkingSpace parkingSpace)
        {
            if (ModelState.IsValid)
            {
                db.Entry(parkingSpace).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.GarageId = new SelectList(db.Garages, "Id", "Name", parkingSpace.GarageId);
            return View(parkingSpace);
        }

        // GET: ParkingSpaces/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ParkingSpace parkingSpace = db.ParkingSpaces.Find(id);
            if (parkingSpace == null)
            {
                return HttpNotFound();
            }
            return View(parkingSpace);
        }

        // POST: ParkingSpaces/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ParkingSpace parkingSpace = db.ParkingSpaces.Find(id);
            db.ParkingSpaces.Remove(parkingSpace);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GoaGaraget/Views/ParkedVehicles/Checkout.cshtml
@model GoaGaraget.Models.Receipt

@{
    ViewBag.Title = "Checkout";
}

<h2>Checkout</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">

    <h4>Welcome Mr/Mrs @Model.ParkedVehicle.Member.SurName</h4>

    <hr />

    <h4>Receipt</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    Vehicle to checkout:
    <h4>@Model.ParkedVehicle.RegNumber</h4>

    Checked in since
    <h4>@Model.ParkedVehicle.CheckinDate</h4>
    <hr />
    <div>Visit summary @ViewBag.visitHours hours and @ViewBag.visitMinutes minutes</div>
    <div>Your current rate is @Model.ParkedVehicle.Member.Price kr/hour</div>

    <h4>Total price owed: @Model.Cost kr</h4>
    <hr />

    <div class="form-group">
        @*@Html.ActionLink("Back to List", "Index")*@
       <input type="submit" value="Checkout" class="btn btn-danger" />
        
    </div>
</div>
}

GoaGaraget/Views/ParkedVehicles/Create.cshtml
@model GoaGaraget.Models.ParkedVehicleViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>ParkedVehicle</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.RegNumber, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.RegNumber, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.RegNumber, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.VehicleType, "VehicleTypeId", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(m => m.VehicleTypeId, Model.VehicleTypes, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.VehicleTypeId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Color, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Color, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Color, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Brand, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Brand, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Brand, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.NumberOfWheels, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.NumberOfWheels, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NumberOfWheels, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.MemberId, "MemberId", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @*@Html.DropDownList("MemberId", null, htmlAttributes: new { @class = "form-control" })*@
            @Html.DropDownListFor(m => m.MemberId, Model.Members, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.MemberId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

GoaGaraget/Views/ParkedVehicles/Delete.cshtml
@model GoaGaraget.Models.ParkedVehicle

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ParkedVehicle</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.RegNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RegNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Size)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Size)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Color)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Color)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VehicleType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VehicleType.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Brand)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Brand)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NumberOfWheels)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumberOfWheels)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CheckinDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CheckinDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

GoaGaraget/Views/ParkedVehicles/Index.cshtml
@model IEnumerable<GoaGaraget.Models.ParkedVehicle>

@{
    ViewBag.Title = "Index";
}
@section Stats{
    @Html.Action("Statistics", "ParkedVehicles")
}
@section Styles{
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/dataTables.bootstrap.min.css">
}
@section scripts{
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#parkedVehicleTable').DataTable();
        });
    </script>
}
<h2>Vehicle Register</h2>

<p>
    @Html.ActionLink("Register vehicle", "Create", new { }, new { @class = "btn btn-success" })
</p>
<table id="parkedVehicleTable" class="table table-striped table-bordered" cellspacing="0" ">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Member)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.RegNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Size)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.VehicleType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NumberOfWheels)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CheckinDate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Member.FirstName)
                    @Html.DisplayFor(modelItem => item.Member.SurName)
                </td>
                <td>
                    <div class="btn-group">
                        @{
                            if (item.ParkingSpaces.Count > 0)
                            {
                                @Html.ActionLink("Checkout", "Checkout", new { id = item.Id }, new { @class = "btn btn-warning btn-xs" })
                            }
                            else
                            {
                                @Html.ActionLink("Park", "Park", new { id = item.Id }, new { @class = "btn btn-success btn-xs" })
                            }
                        }
                    </div>
                    @Html.DisplayFor(modelItem => item.RegNumber)

                </td>
                <td>
                    <div class="btn-group">
                        @{
                            if (item.ParkingSpaces.Count > 0)
                            {

                                foreach (var ps in item.ParkingSpaces)
                                {
                                    @Html.ActionLink(ps.Id.ToString(), "Details", "ParkingSpaces", new { id = ps.Id }, new { @class = "btn btn-success btn-xs" })
                                }

                            }
                            else
                            {

                                for (int i = 0; i < @item.Size; i++)
                                {
                                    <button class="btn btn-xs">|</button>
                                }
                            }

                        }
                    </div>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.VehicleType.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NumberOfWheels)
                </td>
                <td>
                    @item.CheckinDate.ToString("")
                </td>
                <td>

                    <div class="btn-group">

                        @Html.ActionLink("Details", "Details", new { id = item.Id }, new { @class = "btn btn-primary btn-xs" })

                        <div class="btn-group">
                            <button type="button" class="btn btn-primary btn-xs dropdown-toggle" data-toggle="dropdown">
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu" role="menu">
                                <li>
                                    @Html.ActionLink("Edit", "Edit", new { id = item.Id })
                                </li>
                                <li>
                                    @Html.ActionLink("Stats", "Statistics", new { id = item.Id })
                                </li>
                                <li>
                                    @Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { @class = "btn-danger" })

                                </li>
                            </ul>
                        </div>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>