GoaGaraget/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GoaGaraget.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult ParkingFull()
        {
            ViewBag.Message = "Sorry, Parking cannot currently fit this vehicle.";

            return View();
        }
    }
}

GoaGaraget/Controllers/MembersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GoaGaraget.DataAccessLayer;
using GoaGaraget.Models;

namespace GoaGaraget.Controllers
{
    public class MembersController : Controller
    {
        private GarageDbContext db = new GarageDbContext();

        // GET: Members
        public ActionResult Index()
        {
            return View(db.Members.ToList());
        }

        // GET: Members/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Member member = db.Members.Find(id);
            if (member == null)
            {
                return HttpNotFound();
            }
            return View(member);
        }

        // GET: Members/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Members/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,FirstName,SurName,Pin,Price,PersonNumber")] Member member)
        {
            if (ModelState.IsValid)
            {
                db.Members.Add(member);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(member);
        }

        // GET: Members/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Member member = db.Members.Find(id);
            if (member == null)
            {
                return HttpNotFound();
            }
            return View(member);
        }

        // POST: Members/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,FirstName,SurName,Pin,PersonNumber")] Member member)
        {
            if (ModelState.IsValid)
            {
                db.Entry(member).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(member);
        }

        // GET: Members/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Member member = db.Members.Find(id);
            if (member == null)
            {
                return HttpNotFound();
            }
            return View(member);
        }

        // POST: Members/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Member member = db.Members.Find(id);
            db.Members.Remove(member);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GoaGaraget/Controllers/ParkedVehiclesController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GoaGaraget.DataAccessLayer;
using GoaGaraget.Models;

namespace GoaGaraget.Controllers
{
    public class ParkedVehiclesController : Controller
    {
        private GarageDbContext db = new GarageDbContext();

        // GET: ParkedVehicles
        public ActionResult Index()
        {
            return View(db.ParkedVehicles.ToList());
        }
        public ActionResult SimpleIndex()
        {
            List<ParkedVehicleListModel> pvlm = new ParkedVehiclesListModel().Simplify(db.ParkedVehicles.ToList());
            return View(pvlm);
        }

        // GET: ParkedVehicles/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ParkedVehicle parkedVehicle = db.ParkedVehicles.Find(id);
            if (parkedVehicle == null)
            {
                return HttpNotFound();
            }
            return View(parkedVehicle);
        }

        // GET: ParkedVehicles/Statistics/5?
        public ActionResult Statistics(int? id)
        {
            if (id == null)
            {
                StatisticModel sm = new StatisticModel(db.ParkedVehicles.ToList());
                return PartialView("_Statistics", sm);
            }
            else
            {
                ParkedVehicle parkedVehicle = db.ParkedVehicles.Find(id);
                if (parkedVehicle != null)
                {
                    StatisticModel sm = new StatisticModel(parkedVehicle);
                    return View("Statistics", sm);
                }
            }
            return View("Index");
        }

        // GET: ParkedVehicles/Park/5
        public ActionResult Park(int? id)
        {

            if (id == null)
            {
                return View();
            }
            else
            {
                ParkedVehicle parkedVehicle = db.ParkedVehicles.Find(id);
                ParkingSpace[] parkingSpaces = db.ParkingSpaces.ToArray();
                ParkingModel pm = new ParkingModel();
                pm.ParkedVehicle = parkedVehicle;
                if (parkedVehicle.VehicleType.Id == 2)
                {
                    pm.AvailableParkingSpaces = new Functionalities.DoIt().GetAvailableMCParkingSpaces(parkingSpaces);

                }
                else
                {
                    pm.AvailableParkingSpaces = new Functionalities.DoIt().GetAvailableParkingSpaces(parkedVehicle.Size, parkingSpaces);
                }
                pm.ParkedVehicleId = (int)id;
                ViewBag.ParkingSpaceId = new SelectList(pm.AvailableParkingSpaces, "Id", "Id");
                //ViewBag.ParkedVehicleId = new SelectList(, "Id", "RegNumber", id);

                if (parkingSpaces[0] != null) pm.ParkingSpaceId = parkingSpaces[0].Id;

                if (parkedVehicle != null)
                {
                    if (pm.AvailableParkingSpaces.Count > 0)
                        return View(pm);
                    else
                        return View(pm); //RedirectToActionPermanent("ParkingFull", "Home");
                }


            }
            return View("Index");
        }

        // POST : ParkedVehicles/Park/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Park([Bind(Include = "ParkedVehicleId, ParkingSpaceId")] ParkingModel parkingModel)
        {
            if (ModelState.IsValid)
            {
                ParkedVehicle parkedVehicle = db.ParkedVehicles.Find(parkingModel.ParkedVehicleId);
                ParkingSpace parkingSpace;
                parkingModel.CreatedAt = DateTime.Now;
                int i = 0;
                if (parkedVehicle.VehicleType.Id == 2)
                {
                    parkingSpace = db.ParkingSpaces.Find(parkingModel.ParkingSpaceId);
                    parkingSpace.IsEmpty = false;
                    parkingSpace.IsMcParkingSpace = true;
                    parkedVehicle.ParkingSpaces.Add(parkingSpace);
                    db.Entry(parkingSpace).State = EntityState.Modified;
                    //parkingSpace.ParkedVehicles.Add(parkedVehicle);
                    parkedVehicle.CheckinDate = DateTime.Now;
                }
                else
                {
                    do
                    {
                        parkingSpace = db.ParkingSpaces.Find(parkingModel.ParkingSpaceId + i);
                        parkingSpace.IsEmpty = false;
                        parkedVehicle.ParkingSpaces.Add(parkingSpace);
                        db.Entry(parkingSpace).State = EntityState.Modified;
                        parkingSpace.ParkedVehicles.Add(parkedVehicle);
                        i++;
                    } while (i < parkedVehicle.Size);
                    parkedVehicle.CheckinDate = DateTime.Now;
                }
                db.Entry(parkedVehicle).State = EntityState.Modified;
                db.Configuration.ValidateOnSaveEnabled = false;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(parkingModel);
        }

        // GET: ParkedVehicles/Create
        public ActionResult Create()
        {
            Functionalities.DoIt doIt = new Functionalities.DoIt();
            //ViewBag.MemberId = new SelectList(db.Members, "Id", "PersonNumber");
            //ViewBag.VehicleTypeId = new SelectList(db.VehicleTypes, "Id", "Name");

            ParkedVehicleViewModel pvvm = new ParkedVehicleViewModel();
            pvvm.Members = new SelectList(db.Members.ToList(), "Id", "Firstname");
            pvvm.VehicleTypes = new SelectList(db.VehicleTypes.ToList(), "Id", "Name");

            return View(pvvm);
        }

        // POST: ParkedVehicles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MemberId,RegNumber,Color,VehicleTypeId,Brand,NumberOfWheels")] ParkedVehicleViewModel pvvm)
        {
            VehicleType vt = db.VehicleTypes.Single(v => v.Id == pvvm.VehicleTypeId);
            ParkedVehicle parkedVehicle = new ParkedVehicle(pvvm.Member, pvvm.RegNumber, pvvm.Color, vt, pvvm.Brand, pvvm.NumberOfWheels, DateTime.Now);
            parkedVehicle.Member = db.Members.Single(m => m.Id == pvvm.MemberId);
            parkedVehicle.VehicleType = vt;

            if (ModelState.IsValid)
            {
                parkedVehicle.Size = parkedVehicle.VehicleType.Size;
                db.ParkedVehicles.Add(parkedVehicle);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            pvvm.Members = new SelectList(db.Members.ToList(), "Id", "PersonNumber");
            pvvm.VehicleTypes = new SelectList(db.VehicleTypes.ToList(), "Id", "Name");
            return View(pvvm);
        }



        // GET: ParkedVehicles/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ParkedVehicle parkedVehicle = db.ParkedVehicles.Find(id);
            if (parkedVehicle == null)
            {
                return HttpNotFound();
            }
            ParkedVehicleInputModel parkedVehicleInput = new ParkedVehicleInputModel
            {
                Id = parkedVehicle.Id,
                RegNumber = parkedVehicle.RegNumber,
                Color = parkedVehicle.Color,
                Brand = parkedVehicle.Brand,
                NumberOfWheels = parkedVehicle.NumberOfWheels
            };
            return View(parkedVehicleInput);
        }

        // POST: ParkedVehicles/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,RegNumber,Color,Type,Brand,NumberOfWheels,CheckinDate")] ParkedVehicleInputModel parkedVehicleInput)
        {
            if (ModelState.IsValid)
            {
                ParkedVehicle parkedVehicle = db.ParkedVehicles.Find(parkedVehicleInput.Id);
                parkedVehicle.Id = parkedVehicleInput.Id;
                parkedVehicle.Color = parkedVehicleInput.Color;
                parkedVehicle.Brand = parkedVehicleInput.Brand;
                parkedVehicle.NumberOfWheels = parkedVehicleInput.NumberOfWheels;
                db.Entry(parkedVehicle).State = EntityState.Modified;
                db.Configuration.ValidateOnSaveEnabled = false;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(parkedVehicleInput);
        }

        // GET: ParkedVehicles/Checkout/5
        public ActionResult Checkout(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ParkedVehicle parkedVehicle = db.ParkedVehicles.Find(id);
            if (parkedVehicle == null)
            {
                return HttpNotFound();
            }
            Receipt receipt = new Receipt();
            receipt.ParkedVehicle = parkedVehicle;
            new Functionalities.Calculate().UpdateReceipt(receipt);
            ViewBag.visitHours = (receipt.CheckoutAt - receipt.CheckinAt).Hours;
            ViewBag.visitMinutes = (receipt.CheckoutAt - receipt.CheckinAt).Minutes;
            return View(receipt);
        }

GoaGaraget/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>We thrive to make GoaGarage the most Goa Garage&trade; in the World.</p>

GoaGaraget/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    Lexicon<br />
    Liljeholmen, Sweden<br />
    <abbr title="Phone">P:</abbr>
    0735-082358
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

GoaGaraget/Views/Home/Index.cshtml
@section Styles{
    <link href="https://fonts.googleapis.com/css?family=Faster+One" rel="stylesheet">
}
@{
    ViewBag.Title = "Home Page";
}
@section Stats{
    @Html.Action("Statistics", "ParkedVehicles")
}


<div class="jumbotron text-center gl" style="background-image:url('../../Content/goaGarageIntroBackground.jpg')" ;
     background-size: cover">

    <div class="text-block" style="border:solid 5px white; padding:10px;width:500px;bottom: 20px;right: 20px;background-color: rgba(78, 78, 78, 0.8);color: white;padding-left: 20px;padding-right: 20px;">
        <h1 style="font-family: 'Faster One', cursive;">goaGarage</h1>
        <p class="lead">Worlds most Goa Garage</p>
    </div>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Member Register</h2>
        <p>
            Register in member register.
        </p>
        <p>
            <div class="btn-group">
                @Html.ActionLink(" List Members", "Index", "Members", new { }, new { @class = "btn btn-primary btn-lg " })
                <button type="button" class="btn btn-primary btn-lg dropdown-toggle" data-toggle="dropdown">
                    <span class="caret"></span>
                </button>
                <ul class="dropdown-menu" role="menu">
                    <li>@Html.ActionLink(" Register", "Create", "Members")</li>
               </ul>
            </div>

            <div class=".btn-group-vertical">



            </div>
        </p>
    </div>
    <div class="col-md-4">
        <h2>Goa Garage</h2>
        <p>Park vehicle from register.</p>
        <p>
            <div class="btn-group">
                @Html.ActionLink(" List Vehicles", "SimpleIndex", "ParkedVehicles", new { }, new { @class = "btn btn-primary btn-lg " })
                <button type="button" class="btn btn-primary btn-lg dropdown-toggle" data-toggle="dropdown">
                    <span class="caret"></span>
                </button>
                <ul class="dropdown-menu" role="menu">
                    <li>@Html.ActionLink(" Detailed List", "Index", "ParkedVehicles")</li>
                    <li>@Html.ActionLink(" Register Vehicle", "Create", "ParkedVehicles")</li>

                    @*<li>@Html.ActionLink(" Remove", "Remove", "ParkedVehicles")</li> TODO - Interface for search regNumber and delete TODO - Interface for search regNumber and delete*@
                </ul>
            </div>

            <div class=".btn-group-vertical">



            </div>
            @*<div class="btn-group">
            @Html.ActionLink(" Park", "Park", "ParkedVehicles", new { }, new { @class = "btn btn-success btn-lg" })
            @Html.ActionLink(" Checkout", "Checkout", "ParkedVehicles", new { }, new { @class = "btn btn-warning btn-lg" })
        </div>*@
        </p>
    </div>
    <div class="col-md-4">
        <h2>Statistics</h2>
        <p>
            See whats happening in the garage.
        </p>
        <p>
            <div class="btn-group">
                @Html.ActionLink(" More..", "Statistics", "ParkedVehicles", new { }, new { @class = "btn btn-info btn-lg glyphicon glyphicon-globe" })
            </div>
        </p>
    </div>
</div>

GoaGaraget/Views/Home/ParkingFull.cshtml
@{
    ViewBag.Title = "Parking Full";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>


<div>
    <img src="~/Content/garage-full-parking-lot-sign.png" alt="Parking Full" width="400px"/>

</div>



<p>Sorry to say that the garage does not currently have space for this vehicle.</p>

<h4>Welcome back later...</h4>